### ISSUE TITLE
Exception.message is not a thing

### ISSUE THREAD

**Issue by jarekwg** [jkeyes/python-docraptor#9]
> A `message` attribute was added to the built-in exceptions in Python 2.5. It was however deprecated already in Python 2.6 and removed in Python 3.

`DocRaptorRequestException` assumes this attribute always exists.

This led to some very cryptic errors coming out of our production code when docraptor had a hiccup earlier this week.

**Comment by jkeyes** [comment]
Merged to master and version `1.2.3` uploaded to PyPI.
